#!/usr/bin/env python3
"""The firmware patches are structurally sound.

These files are the only thing standing between an upstream checkout and the
build Frank flashes, and they are regenerated by hand whenever the overlay
changes. A hunk header whose line counts do not match its body applies at the
wrong offset or not at all -- and the failure lands in the middle of an Arduino
build, as an error about upstream code that is not actually wrong.

This checks what can be checked without the upstream tree present: that every
patch parses, that each hunk's declared line counts match the lines it actually
carries, that the applier's own parser accepts them, and that the guards which
keep the overlay dormant are all still paired.
"""
import os
import re
import sys
import importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FAILS = []


def ck(ok, msg):
    print("  [%s] %s" % ("PASS" if ok else "FAIL", msg))
    if not ok:
        FAILS.append(msg)


def load_applier():
    spec = importlib.util.spec_from_file_location(
        "patch_openfire", os.path.join(ROOT, "tools", "patch_openfire.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def check_patch(path, applier):
    name = os.path.basename(path)
    with open(path) as f:
        lines = f.readlines()
    ck(lines[0].startswith("--- a/") and lines[1].startswith("+++ b/"),
       "%s: names the file it patches" % name)

    hunks = 0
    ok_counts = True
    i = 2
    while i < len(lines):
        m = re.match(r"@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@", lines[i])
        if not m:
            i += 1
            continue
        hunks += 1
        want_old = int(m.group(2) or 1)
        want_new = int(m.group(4) or 1)
        got_old = got_new = 0
        j = i + 1
        while j < len(lines) and not lines[j].startswith("@@"):
            c = lines[j][0] if lines[j] else " "
            if c == "-":
                got_old += 1
            elif c == "+":
                got_new += 1
            elif c in (" ", "\n"):
                got_old += 1
                got_new += 1
            elif c == "\\":
                pass                     # "\ No newline at end of file"
            j += 1
        if (got_old, got_new) != (want_old, want_new):
            ok_counts = False
            print("      hunk at line %d claims -%d,+%d but carries -%d,+%d"
                  % (i + 1, want_old, want_new, got_old, got_new))
        i = j
    ck(hunks > 0, "%s: has hunks" % name)
    ck(ok_counts, "%s: every hunk's line counts match its body" % name)

    # The applier is the thing that will actually read this file on Frank's
    # machine, so its own parser gets a say rather than only this test's.
    try:
        parsed = applier.parse_hunks(applier.read(path))
        ck(len(parsed) == hunks,
           "%s: the applier's parser finds the same %d hunks" % (name, hunks))
    except Exception as e:
        ck(False, "%s: the applier's parser refused it (%s)" % (name, e))

    # Every overlay guard must be paired. An unbalanced #ifdef in a patch
    # compiles fine in one configuration and fails in the other, which is the
    # slowest possible way to find out.
    added = [l[1:] for l in lines if l.startswith("+")]
    body = "".join(added)
    opens = len(re.findall(r"^\s*#if(?:def|ndef)?\b", body, re.M))
    closes = len(re.findall(r"^\s*#endif\b", body, re.M))
    ck(opens == closes,
       "%s: the guards it adds are balanced (%d #if / %d #endif)"
       % (name, opens, closes))


def main():
    applier = load_applier()
    pdir = os.path.join(ROOT, "patches", "rp2040")
    patches = sorted(p for p in os.listdir(pdir) if p.endswith(".patch"))
    ck(len(patches) >= 3, "the rp2040 patch set is present (%d files)"
       % len(patches))
    for p in patches:
        check_patch(os.path.join(pdir, p), applier)

    # The one property the whole overlay rests on: nothing it adds to the
    # firmware may run unless USE_AIM_PIPELINE is defined. A patch that adds
    # unguarded code changes the stock build for everyone.
    for p in patches:
        with open(os.path.join(pdir, p)) as f:
            txt = f.read()
        guards = ("USE_AIM_PIPELINE" in txt) or ("LIGHTGUN_RECOIL_FX" in txt)
        ck(guards, "%s: its additions sit behind an overlay guard" % p)

    print("\npatch shape: %s (%d failures)"
          % ("ALL PASS" if not FAILS else "FAILED", len(FAILS)))
    return 1 if FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
